### ISSUE TITLE
Use nvbio to develop program

### ISSUE THREAD

**Issue by nevergonefan** [NVlabs/nvbio#16]
I want to use nvbio to implement an algorithm for alignment, but I don't know how to include nvbio in my project? Should I cmake it first and include it as a header file?

**Comment by nevergonefan** [comment]
I have compiled nvbio and run the examples, but I don't know how to use nvbio as a lib in my project? I am not famaliar to cmake and makefile...

**Comment by r-barnes** [comment]
@nevergonefan : If you're not familiar with cmake and makefile, this isn't really the appropriate place to get help with them. Once you've built nvbio, you can find a `libnvbio.a` file under your build directory. This is the library. The header files are included in the `nvbio` directory (not under build). Once you've located these you'll need to use StackOverflow or some other site to find out how to build a project using them.
