### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ejfresch** [NVlabs/nvbio#2]
Hello!
I have some problems downloading the latest release of nvbio. According to the web site (http://nvlabs.github.io/nvbio/index.html) the latest release is 0.9.99, but the tags of the repository stop at 0.9.9.3

Thanks a lot for this fantastic software!

**Comment by jpantaleoni** [comment]
Hi Luca,

we are not currently tagging releases on a frequent basis, though we should probably start doing it more regularly.
At the moment, I would just recommend to take the top of the tree.

-jacopo

**Comment by ejfresch** [comment]
Hi Jacopo, 
thanks for your quick answer. I was asking because our users are using nvbowtie and when they will publish papers based on these analyses they should provide the version of the software. For the moment I will use the hashes of your commits as reference. 


-Luca

**Comment by jpantaleoni** [comment]
I have just tagged version 0.9.99 - I will start doing this more regularly

**Comment by ejfresch** [comment]
Thanks a lot Jacopo!

-Luca
