### ISSUE TITLE
Updated GPU architectures?

### ISSUE THREAD

**Issue by ndt26** [NVlabs/nvbio#20]
I tried to specify a newer GPU architectures as follows:

cmake -DGPU_ARCHITECTURE=sm_61

only to get the following error:

nvcc fatal   : Value 'sm_61' is not defined for option 'gpu-architecture'
CMake Error at nvbio_generated_file_bwt_bgz.cu.o.cmake:207 (message):
  Error generating

If this is a simple update to apply, it would be much appreciated!

Thanks!
Nate

**Comment by r-barnes** [comment]
@ndt26 : master has just been updated to support newer versions of CUDA and GCC. I am able to get compilation using the following:
```
CXX=g++-8 CC=gcc-8 cmake -DCMAKE_BUILD_TYPE=Release -DGPU_ARCHITECTURE=sm_61 ..
```

@foertter : I think this can be closed.

**Comment by ndtippens** [comment]
Did you try running nvbio-test after compilation?

Mine is failing:

CUDA 10.2
Ubuntu18.04 LTS, 4.15.0-76

info    : work_queue test... started
info    :   testing multi-pass work-queue:
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  for_each: failed to synchronize: cudaErrorInvalidValue: invalid argument
Aborted (core dumped)

**Comment by r-barnes** [comment]
@ndt26 : I don't encounter that problem. Nonetheless, it's a separate issue than the one which opened this thread.

**Comment by jarushi13** [comment]
Hi,
@ndt26 I am facing the exact same issue. My DGPU_ARCHITETURE is sm_35 and CUDA version is 10.1.243. How did you fix the issue?

Thanks a lot.
