### ISSUE TITLE
make -j8 get error used https://github.com/vmiheer/nvbio

### ISSUE THREAD

**Issue by yubau1112** [NVlabs/nvbio#21]
[make_j8.log](https://github.com/NVlabs/nvbio/files/2720323/make_j8.log)

Hi, @vmiheer i clone you provide version but i still get error 
How to solve it ?
thanks your time!

**Comment by richursa** [comment]
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

this is the error which I receive when running make -j8

**Comment by vmiheer** [comment]
I'll upload some fixes soon.

**Comment by vmiheer** [comment]
Hi @yubau1112, sorry for late reply but please https://github.com/NVlabs/nvbio/issues/22#issuecomment-483868163. 😄
